name: movie_app
description: An awesome movie app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  http: ^0.12.2
  flutter_bloc: ^6.1.2
  url_launcher: ^5.7.10
  shared_preferences: ^0.5.12+4
  carousel_slider: ^3.0.0
  dots_indicator: ^1.2.0
  sqflite: ^1.3.2+3
  path_provider: ^1.6.27
  extended_image: ^1.5.0
  flutter_typeahead: ^2.0.0
  flutter_local_notifications: ^4.0.1+1
  flutter_native_splash: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: PaytoneOne
      fonts:
        - asset: assets/fonts/PaytoneOne-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

flutter_native_splash:
  image: assets/images/logo_bg.png
  color: 1C1A24